# Generated by Django 4.2.7 on 2023-11-19 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_store_storeinventory_store_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='closing_hour',
            field=models.IntegerField(default=18),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='store',
            name='opening_hour',
            field=models.IntegerField(default=9),
            preserve_default=False,
        ),
    ]
